name: tests

on:
  push:
    tags:
      - v*
    branches:
      - actions
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    container: madflojo/ubuntu-build
    steps:
    - uses: actions/checkout@v3
    # Using this instead of actions/setup-go to get around an issue with act
    - name: Install Go
      run: |
           curl -L https://go.dev/dl/go1.19.9.linux-amd64.tar.gz | tar -C /usr/local -xzf -
    - name: Execute Tests
      run: |
        /usr/local/go/bin/go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
